stack/app.py, stack/config.py
=> More config

README.md, setup.py, tests/conftest.py, tests/routes/v1/test_metadata.py, tests/routes/v1/test_ogc.py, tests/routes/v1/test_tiles.py, titiler/api/api_v1/endpoints/metadata.py, titiler/api/api_v1/endpoints/ogc.py, titiler/api/api_v1/endpoints/operations.py, titiler/api/api_v1/endpoints/tiles.py, titiler/api/deps.py, titiler/custom/tms.py, titiler/models/OGC.py, titiler/ressources/common.py, titiler/ressources/enums.py, titiler/templates/index.html, titiler/templates/simple.html, titiler/templates/wmts.xml
This PR does
- switch to morecantile / rio-tiler-crs
- refactor endpoints
- update docs
=> Switch to Morecantile

CHANGES.txt, setup.py, tests/routes/test_cog.py, tests/routes/test_mosaic.py, tests/routes/test_stac.py, titiler/api/endpoints/stac.py, titiler/errors.py, titiler/main.py
- Adds fastapi exception handlers.
Closes #41
=> Add exception handlers

CHANGES.txt, tests/routes/test_cog.py, titiler/endpoints/cog.py, titiler/endpoints/mosaic.py, titiler/endpoints/stac.py, titiler/main.py, titiler/ressources/responses.py, titiler/settings.py
=> add cache control middleware and remove useless Response

setup.py, tests/routes/test_mosaic.py, tests/routes/test_stac.py, titiler/endpoints/cog.py, titiler/endpoints/mosaic.py, titiler/endpoints/stac.py, titiler/errors.py, titiler/ressources/enums.py
=> update for latest cogeo-mosaic and rio-tiler

CHANGES.txt, setup.py, tests/routes/test_mosaic.py, titiler/endpoints/cog.py, titiler/endpoints/mosaic.py
=> add X-Assets in headers and fix breaking changes

CHANGES.txt, setup.py, tests/routes/test_cog.py, titiler/endpoints/cog.py
=> add cog validation endpoint

titiler/endpoints/cog.py, titiler/endpoints/mosaic.py, titiler/endpoints/stac.py, titiler/ressources/common.py
=> use common image endpoint params

tests/routes/test_cog.py, tests/routes/test_mosaic.py, titiler/endpoints/cog.py, titiler/endpoints/mosaic.py, titiler/endpoints/stac.py, titiler/endpoints/tms.py, titiler/models/cog.py, titiler/templates/wmts.xml
This PR does:
- closes #74 : use starlette url_for, for route matching 
- add wmts endpoint for stac 
- fix possible bugs in mosaic wmts (not forwarding tile options)
=> use url_for for route matching, refactor wmts endpoints

CHANGES.md, setup.py, tests/test_factories.py, titiler/endpoints/cog.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py
=> Router url for

.env.example, CHANGES.md, docs/concepts/tiler_factories.md, stack/app.py, stack/config.py, tests/conftest.py, tests/routes/test_mosaic.py, titiler/dependencies.py, titiler/settings.py
=> Remove mosaicid path translation

.env.example, CHANGES.md, docs/deployment/settings.md, stack/app.py, stack/config.py, tests/conftest.py, tests/routes/test_cog.py, titiler/main.py, titiler/settings.py
=> Resolve mixing env

CHANGES.md, setup.py, tests/routes/test_cog.py, titiler/dependencies.py, titiler/endpoints/factory.py, titiler/ressources/common.py, titiler/utils.py
=> NumpyTile output

CHANGES.md, tests/test_CustomAPIRoute.py, titiler/custom/routing.py
same has #107 #106 but totally optional!
=> Custom api route

CHANGES.md, setup.py, tests/test_factories.py, titiler/dependencies.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py
=> refactor deps to better match BaseReader methods

CHANGES.md, tests/routes/test_cog.py, tests/routes/test_mosaic.py, tests/test_main.py, titiler/endpoints/factory.py, titiler/main.py, titiler/middleware.py, titiler/utils.py
=> add 'Server-Timing' in headers and create middleware sub-module

docs/deployment/ecs.md, stack/app.py, stack/config.py
=> update ECS config and notes

CHANGES.md, setup.py, tests/routes/test_cog.py, titiler/main.py, titiler/middleware.py
=> revert to gzip compression only

docs/concepts/dependencies.md
=> Remove reference to TMSTilerFactory

CHANGES.md, titiler/endpoints/factory.py
=> slit tile methods for MosaicTilerFactory

CHANGES.md, titiler/main.py, titiler/settings.py
=> add environment variables to control default endpoints

CHANGES.md, titiler/endpoints/factory.py, titiler/models/mosaic.py
=> Overwrite mosaic

.github/workflows/ci.yml
=> WIP resolve AWS docker login

CHANGES.md, titiler/dependencies.py, titiler/endpoints/stac.py
=> move STACTiler dependencies in titiler.dependencies

CHANGES.md, titiler/dependencies.py
=> add `rio_tiler.io.MultiBandReader` bands dependencies

.github/workflows/deploy_mkdocs.yml, .gitignore, CONTRIBUTING.md, mkdocs.yml
=> add API docs

CHANGES.md, setup.py
=> update requirements and python version

deployment/aws/cdk/app.py, deployment/aws/cdk/config.py, docs/deployment/aws/intro.md
=> update cdk code and move env in settings

docs/advanced/APIRoute_and_environment_variables.md
Just made some minor text edits and added a question about the link
=> Minor text edits

docs/advanced/performance_tuning.md, mkdocs.yml
Closes https://github.com/developmentseed/titiler/issues/240
I'd love help for: GDAL_CACHEMAX, GDAL_DATA, PROJ_LIB.
=> Start of GDAL config settings doc

MANIFEST.in, scripts/publish, setup.cfg, setup.py
=> add setup for titiler metapackage

docs/examples/code/tiler_with_custom_colormap.md, mkdocs.yml
ref https://github.com/developmentseed/titiler/discussions/299
=> add example for custom colormap dependencies

deployment/k8s/titiler/templates/deployment.yaml, deployment/k8s/titiler/values.yaml
Hey
Small PR to add support for setting a serviceAccountName in the helm chart
=> Helm - Add support for serviceAccountName

deployment/k8s/titiler/templates/_helpers.tpl, deployment/k8s/titiler/templates/deployment.yaml, deployment/k8s/titiler/templates/service.yaml
to avoid code duplication
cc @geospatial-jeff @emmanuelmathot
=> [k8s] Define labels in _helpers.tpl

CHANGES.md, titiler/application/titiler/application/main.py
=> add ToTalTime middleware last so it is executed first

deployment/aws/cdk/app.py, deployment/aws/cdk/config.py, docs/deployment/k8s.md, mkdocs.yml
=> fix possible deployement issue and update docs

Dockerfile
ref: https://github.com/developmentseed/titiler/discussions/325
=> remove rasterio version pin

deployment/aws/cdk/app.py, deployment/aws/cdk/config.py, deployment/aws/lambda/Dockerfile
=> limit AWS S3 access

CHANGES.md, Dockerfile
**Related issue** : #379 
Update root certificates at every container build
=> update root certificates at every build

docs/examples/notebooks/Create_CustomSentinel2Tiler.ipynb
The `backend_options` arg was renamed in 3.0.0rc2. This PR updates the notebook to use the new arg name.
https://developmentseed.org/cogeo-mosaic/release-notes.html#300rc2-2021-02-25
=> make compatible with cogeo-mosaic 3.0.0

CHANGES.md, deployment/aws/lambda/Dockerfile, setup.cfg, setup.py, src/titiler/application/setup.py, src/titiler/application/titiler/application/version.py, src/titiler/core/setup.py, src/titiler/core/titiler/core/version.py, src/titiler/mosaic/setup.py, src/titiler/mosaic/titiler/mosaic/version.py
update requirements and versions
=> update requirements and versions

deployment/README.md, deployment/azure/.funcignore, deployment/azure/.gitignore, deployment/azure/README.md, deployment/azure/app/__init__.py, deployment/azure/app/function.json, deployment/azure/host.json, deployment/azure/requirements.txt, docs/deployment/azure.md, docs/deployment/k8s.md, mkdocs.yml
@robintw would you be able to review this? 🙏
=> add Microsoft Azure function deployment

CHANGES.md, src/titiler/application/setup.py, src/titiler/core/setup.py, src/titiler/core/tests/test_routing.py
ref: [#134 ](https://github.com/developmentseed/titiler/issues/366#issuecomment-911945426)
FastAPI>=0.73 fixed the issue with Tuple in pydantic model 🥳
=> update fastapi requirements

CHANGES.md, docs/advanced/tiler_factories.md, docs/endpoints/stac.md, src/titiler/application/titiler/application/routers/stac.py, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py
ref https://github.com/developmentseed/titiler/discussions/429
`revert` change made in `0.4.0` for the MultiBaseTilerFactory statistic, and add `asset_statistics`.
=> revert to merged statistics for MultiBaseTilerFactory

docs/examples/code/mosaic_from_urls.md
In one of the examples in the documentation a type import was missing
=> Add missing type import

docs/src/examples/code/tiler_with_cache.md
In [tile with cache example](https://github.com/developmentseed/titiler/blob/master/docs/src/examples/code/tiler_with_cache.md) documentation
For #502 updating tile with cache example documentation by adding notes about aioredis version, adding env file example, adding alias arguments into `@cached()`, and adding notes about how to add cache into another endpoints.
=> Updating tiler with cache example in documentation

CHANGES.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py
fix https://github.com/stac-utils/titiler-pgstac/issues/77 and another issue introduced with latest morecantile version
=> replace path_param in router prefix

CHANGES.md, src/titiler/core/tests/test_logger_middleware.py, src/titiler/core/tests/test_timing_middleware.py, src/titiler/core/titiler/core/middleware.py
=> remove BaseHTTPMiddleware

CHANGES.md, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
ref https://github.com/developmentseed/titiler/discussions/577
=> add Strict mode for mosaic zoom level

CHANGES.md, src/titiler/core/pyproject.toml, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
=> apply colormap before checking the output format

CHANGES.md, src/titiler/core/titiler/core/factory.py
=> make sure URL is a String

CHANGES.md, src/titiler/core/pyproject.toml
=> set maximum version for fastapi

deployment/aws/cdk/app.py, deployment/aws/lambda/Dockerfile, deployment/aws/package-lock.json, deployment/aws/package.json, deployment/aws/requirements-cdk.txt, docs/src/deployment/aws/ecs.md, docs/src/deployment/aws/lambda.md, docs/src/deployment/aws/sam.md
=> update CDK and Lambda Python

CHANGES.md, CONTRIBUTING.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py
=> add dst-crs

CHANGES.md, src/titiler/extensions/titiler/extensions/cogeo.py
ref https://github.com/NASA-IMPACT/veda-backend/issues/187
=> use titiler custom JSONResponse to handle NaN values

.github/workflows/benchmark.yml
- create gh-benchmarks branch
- add docs
=> add benchmark comparison

CHANGES.md, src/titiler/extensions/titiler/extensions/templates/cog_viewer.html, src/titiler/extensions/titiler/extensions/templates/stac_viewer.html
ref: https://stamen.com/here-comes-the-future-of-stamen-maps/
=> replace stamen basemap by osm

src/titiler/application/tests/routes/test_cog.py, src/titiler/core/tests/test_dependencies.py, src/titiler/core/tests/test_factories.py, src/titiler/extensions/tests/test_wms.py, src/titiler/extensions/titiler/extensions/templates/wms_1.0.0.xml, src/titiler/extensions/titiler/extensions/templates/wms_1.1.1.xml, src/titiler/extensions/titiler/extensions/templates/wms_1.3.0.xml, src/titiler/extensions/titiler/extensions/wms.py
@benjaminleighton I made some edits (https://github.com/developmentseed/titiler/commit/1a2bf7f93a27efc61dc5f2bd5e75c9e21432a060) on the original PR but couldn't push directly into your fork. 
Basically I did:
- adapt for all the versions
- add type info 
- fix a possible bug
It will be great if you could 👍 👎
=> WMS get feature (edits from 697)

CHANGES.md, docs/src/advanced/dependencies.md, src/titiler/core/pyproject.toml, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py
=> allow bidx option in multibasetiler

CHANGES.md, src/titiler/core/titiler/core/templates/map.html
=> add buffer to aoi

CHANGES.md, src/titiler/core/pyproject.toml, src/titiler/core/titiler/core/factory.py
see https://cogeotiff.github.io/rio-tiler/advanced/statistics/#adjusting-geometry-align_bounds_with_datasettrue
=> update rio-tiler version and use new options for better statistics

.github/workflows/ci.yml, pyproject.toml, src/titiler/application/pyproject.toml, src/titiler/core/pyproject.toml, src/titiler/extensions/pyproject.toml, src/titiler/mosaic/pyproject.toml
=> add python 3.12

src/titiler/core/titiler/core/algorithm/dem.py
@vincentsarago I just found a stupid mistake of title for terrainrgb algorithm...I am sorry for this...
=> fix: fixed title of terrainrgb algorithm

CHANGES.md, src/titiler/core/pyproject.toml, src/titiler/core/titiler/core/algorithm/dem.py
=> set fastapi limit to >=0.111.0

CHANGES.md, src/titiler/core/titiler/core/resources/responses.py
ref https://github.com/cogeotiff/rio-tiler/pull/755#pullrequestreview-2393716261
=> convert Numpy.Array/Generic for JSON encoding

CHANGES.md, docs/src/advanced/endpoints_factories.md, docs/src/endpoints/cog.md, docs/src/endpoints/mosaic.md, docs/src/endpoints/stac.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/models/OGC.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
=> add OGC tileset list and tileset metadata endpoints

CHANGES.md, src/titiler/core/titiler/core/resources/enums.py
ref https://github.com/developmentseed/titiler-cmr/pull/33
=> add gif mediatype

docs/src/examples/notebooks/Working_with_STAC.ipynb
Commit 962dc605a73fdb4e134c4ad89463cd1e188ce02d moved the location of the STAC docs. This PR adjusts sources to changes.
=> update STAC reference

CHANGES.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/models/responses.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py, src/titiler/mosaic/titiler/mosaic/models/responses.py
closes https://github.com/developmentseed/titiler/issues/959
=> Point to return masked values

.github/workflows/ci.yml, pyproject.toml, src/titiler/application/pyproject.toml, src/titiler/core/pyproject.toml, src/titiler/extensions/pyproject.toml, src/titiler/mosaic/pyproject.toml, src/titiler/xarray/pyproject.toml
Addresses #1057 cc @vincentsarago
=> Add python 3.13, remove 3.8

CHANGES.md, src/titiler/core/pyproject.toml, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
ref https://github.com/developmentseed/titiler/discussions/732
=> switch to URN style

docs/src/examples/code/mosaic_from_urls.md
=> docs: change reader to backend in docs reference to MosaicTiler

docs/src/examples/notebooks/Working_with_STAC.ipynb
=> Issue 1122: Fixed mistake in "Working with STAC" documentation.

CHANGES.md, src/titiler/core/tests/test_algorithms.py, src/titiler/core/titiler/core/algorithm/__init__.py, src/titiler/core/titiler/core/algorithm/math.py
=> add `min`, `max`, `mean`, `median`, `std` and `var` algorithms

CHANGES.md, src/titiler/xarray/tests/test_io_tools.py, src/titiler/xarray/titiler/xarray/io.py
To support this titiler-cmr PR https://github.com/developmentseed/titiler-cmr/pull/52 and address https://github.com/developmentseed/titiler/issues/1170
=> Add datetime to _cast_to_type

CHANGES.md, src/titiler/application/titiler/application/main.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py, src/titiler/xarray/pyproject.toml
=> fix rel values for tiling-scheme links

SECURITY.md, docs/mkdocs.yml, docs/src/security.md
=> add security doc

CHANGES.md, docs/src/user_guide/algorithms.md, src/titiler/core/tests/test_algorithms.py, src/titiler/core/titiler/core/algorithm/__init__.py, src/titiler/core/titiler/core/algorithm/image.py
=> add grayscale and bitonal algorithms
