developmentseed/titiler

titiler/api/utils.py
Use getattr when requesting state.cache to avoid errors when cache no cache is set.
If not using cache_middleware, request.state.cache is not set and causes an error in get_cache. This makes sure that get_cache uses getattr on request.state.
=> Fix for request.state.cache error when no cache is set.

CHANGES.txt, Dockerfiles/ecs/Dockerfile, Dockerfiles/lambda/Dockerfile, README.md, lambda/handler.py, setup.py, tests/conftest.py, tests/routes/test_cog.py, tests/routes/test_stac.py, titiler/api/endpoints/cog.py, titiler/api/endpoints/mosaic.py, titiler/api/endpoints/stac.py
=> update rio-tiler and fix FastAPI issues

CHANGES.md, docs/concepts/tiler_factories.md, setup.py, tests/conftest.py, tests/test_factories.py, titiler/dependencies.py, titiler/endpoints/cog.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py
This PR is another approach for #87 and it does:
- removes morecantile.tms support from TilerFactory (only support WebMercator) and readers don't need TMS support (e.g rio-tiler.io.COGReader)
- adds TMSTilerFactory which support more TMS (needs a TMS friendly Reader like rio_tiler_crs.COGReader)
=> Default to web mercator

CHANGES.md, docs/concepts/tiler_factories.md, tests/test_factories.py, titiler/dependencies.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py
This PR does:
- remove assets options from the default factories
- write an example about Factory class customization
- add dependencies to tilejson and wms for the users to know what options are possible for the tile endpoinds.
=> asset params is only for STAC and for the user to add

README.md, titiler/endpoints/cog.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py, titiler/models/dataset.py
This PR does:
- rename `titiler.models.cog.py` to `titiler.models.dataset.py`
- remove cog* prefix to Bounds, Info and Metadata models
- allow `Union[str, int]` for key in `Metadata.statistics` (as defined in rio-tiler-pds)
=> more generic model (adapt for rio-tiler-pds)

.env.example, docs/deployment/settings.md
Minor documentation updates suggestions based on my deploy experience. The STACK_NAME example contains an invalid character. I'm also including an example on how to define extra ENV vars for lambda, I needed to include that to work with CBERS' requester pays buckets.
=> Valid stack name in documentation; including example for requester pays

README.md, docs/examples/Working_with_CloudOptimizedGeoTIFF.ipynb, docs/examples/Working_with_CloudOptimizedGeoTIFF_simple.ipynb, docs/examples/Working_with_MosaicJSON.ipynb, docs/examples/Working_with_STAC_simple.ipynb, docs/examples/Working_with_nonWebMercatorTMS.ipynb
Adds binder links to the README (to browse the repo) and to each Jupyter Notebook other than the custom Sentinel 2 tiler one
In order to add badges to each Jupyter Notebook, I opened Jupyter Lab, added a badge to the first Markdown section, and saved. Notebooks just have horrible diffs 🤷‍♂️
=> Add binder links

stack/app.py
CDK deploy currently errors because you can't use non-string values as env values.
=> Coerce env values to string

setup.py, tests/routes/test_cog.py, titiler/main.py, tox.ini
Now that mangum and brotli-asgi have new versions, we should restore brotli compression
=> Restore brotli middleware

stack/app.py
From the docstring of `client.images.build`:
```
rm (bool): Remove intermediate containers. The ``docker build``
command now defaults to ``--rm=true``, but we have kept the old
default of `False` to preserve backward compatibility
```
I think when `False`, it doesn't clean up intermediate containers, thus taking up more disk space?
=> Set `rm=True` for building docker containers

CHANGES.md, titiler/dependencies.py
What this PR does:
because titiler is meant to be used as a python module, I think we shouldn't modify the mutable object from rio-tiler and morecantile. 
```
In [1]: from morecantile import tms                                                                                                                                                                                                                                                                                             
In [2]: tms.list() …
```
=> avoid changing mutable TMS and Colormap list by using deepcopy.

lambda/handler.py, titiler/main.py, titiler/middleware.py, titiler/settings.py
closes #138 
- turn off logs 
- add logger middleware (useful when using AWS Lambda)
=> Add logger

CHANGES.md, docs/concepts/APIRoute_and_environment_variables.md, tests/test_CustomAPIRoute.py, titiler/custom/routing.py, titiler/endpoints/factory.py
=> add gdal_config option

CHANGES.md, README.md, docs/concepts/tiler_factories.md, docs/endpoints/cog.md, docs/endpoints/mosaic.md, docs/endpoints/stac.md, docs/intro.md, setup.py, tests/routes/test_cog.py, tests/routes/test_mosaic.py, tests/routes/test_stac.py, tests/test_factories.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py, titiler/ressources/enums.py, titiler/ressources/responses.py, titiler/utils.py, tox.ini
closes #166 
This PR adds a `/info.geojson` route to the Tiler Factories. 
Note: I didn't change the `/info` endpoints to `/info.json` (because this was leading to a 🕳️ , basically if we add info.json, then we should also have metadata.json, bounds.json...)
=> add /info.geojson routes

.gitignore, CHANGES.md, deployment/k8s/titiler/templates/NOTES.txt, deployment/k8s/titiler/templates/ingress.yaml, deployment/k8s/titiler/values.yaml
***Add ingress template in k8s deployment***
In a production k8s cluster, the ingress resource in essential to route request from a public address to a service that loads balance towards several replicas of the deployment.
This PR adds a new template for the ingress following the helm charts conventions and allowing TLS termination
=> ingress template for k8s chart deployment

mkdocs.yml
Adding the [`site_url`](https://www.mkdocs.org/user-guide/configuration/#site_url):
> This will add a link tag with the canonical URL to the generated HTML header.
The edit link isn't strictly necessary. As you can tell, there's already an edit link on titiler pages. The main difference is that the default edit link goes _straight to the editing mode_ on Github. That means that a user who isn't logged in would be immediately greeted with an auth wall. When I was writing docs with mkdocs for my first project, most users wouldn't be on Github, so I wanted them to see the Github docs page before needing to sign in. But here that's probably personal preference.
=> Add edit and site links

tests/test_factories.py, titiler/endpoints/factory.py, titiler/endpoints/mosaic.py
=> Move 'validate' in MosaicTilerFactory class

deployment/aws/cdk/app.py, docs/concepts/customization.md, docs/concepts/mosaics.md, docs/endpoints/mosaic.md, tests/routes/test_mosaic.py, tests/test_factories.py, titiler/endpoints/factory.py
=> remove default create/update endpoint in MosaicTilerFactory

CHANGES.md, tests/routes/test_stac.py, titiler/dependencies.py, titiler/endpoints/factory.py, titiler/endpoints/stac.py, titiler/templates/stac_index.html
=> add MultiBandReader and MultiBaseReader TilerFactories

CHANGES.md, tests/routes/test_cog.py, tests/routes/test_mosaic.py, tests/test_factories.py, tests/test_main.py, titiler/endpoints/factory.py, titiler/main.py, titiler/resources/enums.py
=> make timings and metadata headers optional

Dockerfile, deployment/aws/lambda/Dockerfile
=> Pin rasterio in dockerfiles

.github/workflows/ci.yml, .pre-commit-config.yaml, CHANGES.md, setup.py, titiler/endpoints/factory.py
In cogeo-mosaic backend we are using `backend_options` to pass addition backend options (e.g client) 
cc @kylebarron
=> add backend options to the MosaicTilerFactory

CHANGES.md, tests/test_enums.py, tests/test_factories.py, titiler/endpoints/factory.py, titiler/models/OGC.py, titiler/resources/enums.py
=> use singular for enums

CHANGES.md, docs/concepts/dependencies.md, tests/conftest.py, tests/test_CustomRender.py, titiler/dependencies.py, titiler/endpoints/factory.py
this PR add `**render_params.kwargs` to pass custom render params in image.render method.
ref: https://github.com/developmentseed/titiler/discussions/255
cc @neda-dtu
=> add `**render_params.kwargs` ito pass custom render params

CHANGES.md, docs/concepts/dependencies.md, tests/test_CustomCmap.py, titiler/dependencies.py, titiler/endpoints/factory.py
closes #251 
This PR tries to simplify how we can register colormaps 
```python
from rio_tiler.colormap import cmap
ColorMapNames = Enum(  # type: ignore
"ColorMapNames", [(a, a) for a in sorted(cmap.list())]
)
def ColorMapParams(
color_map: ColorMapNames = Query(None, description="Colormap name",)
) -> Optional[Dict]:
"""Colormap Dependency."""
if color_map:
return cmap.get(color_map.value)
return None
tiler = TilerFactory(colormap_dependency=ColorMapParams)
```
=> make colormap an independent dependency

CHANGES.md, deployment/k8s/titiler/templates/deployment.yaml
Changed probe url from ping to healthz
=> [k8s] Changed probe url from ping to healthz

CHANGES.md, setup.py, tests/routes/test_cog.py, tests/routes/test_mosaic.py, tests/test_CustomCmap.py, titiler/dependencies.py, titiler/endpoints/factory.py, titiler/templates/cog_index.html, titiler/templates/stac_index.html
closes #153  
This PR does:
- rename `color_map` query parameter to `colormap_name` 
- add `colormap` option.
The `colormap` option accepts JSON encoded object in form of:
```
{
"1": {RGB(A)}
}
```
the `{RBG(A)}` value can either be a list of R,G,B (and Alpha) values or an hex color representation
cc @kylebarron @blazetopher
=> add Custom Colormap querystring option

docs/endpoints/cog.md, docs/endpoints/stac.md
Updated details of `colormap` parameter to reference customer JSON encoded colormap.
Added `colormap_name` parameter referencing *rio* colormaps.
closes #272
=> updated colormap parameter details and added colormap_name parameter

CHANGES.md, titiler/application/tests/test_cache_middleware.py, titiler/application/titiler/application/main.py, titiler/application/titiler/application/middleware.py
closes #277 
This PR adds a `exclude_path` option for the CacheControlMiddleware
=> add exclude_path to CacheControlMiddleware

README.md, docs/intro.md, titiler/mosaic/README.md
update instructions for local install to make all packages mutable (-e), general install documentation improvements
The existing directions for running locally with uvicorn only applied mutability `-e` on titiler/core and not application or mosaic, so only changes to core were picked up by reload, even through changes in application or mosaic still triggered a reload -- which was very confusing!
=> fix: update instructions for local install to make all packages mutable

CHANGES.md, titiler/core/tests/test_factories.py, titiler/core/titiler/core/factory.py, titiler/mosaic/tests/test_factory.py, titiler/mosaic/titiler/mosaic/factory.py
=> compare parameters in lowercase

CHANGES.md, docs/endpoints/cog.md, docs/endpoints/stac.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/utils.py
closes #340 
This PR adds 2 new endpoints per TilerFactories
`GET - /statistics`: get stats from a preview of a dataset
`POST - /statistics`: get stats from a feature covering a dataset
Per the HTML specification, `list` must be passed using multiple parameter (e.g `p=1&p=2`) and is also supported in openapi. When we started titiler we (I) didn't knew about this and used `comma delimited string` (e.g `bidx=1,2,3`) to allow list input. In the PR the statistics endpoints have 2 `list` inputs: **c** (categories) and **p** (percentiles). I've choose to keep the name small because those will be repeated in the query_param (e.g `p=1&p=2` to define `percentiles=[1, 2]`).
I'm open to discuss either we should follow the spec or use `comma delimited values`. I've already raised this over …
=> add statistics endpoints

CHANGES.md, docs/endpoints/mosaic.md, src/titiler/mosaic/setup.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
_Background for this PR can be found here: https://github.com/developmentseed/titiler/discussions/350_
This PR adds three new endpoints to Titiler:
```
http://<titiler-host>/mosaicjson/{minx},{miny},{maxx},{maxy}/assets
http://<titiler-host>/mosaicjson/{lon},{lat}/assets
http://<titiler-host>/mosaicjson/{quadkey}/assets
```
Each endpoint returns a list of cogs which overlap the geometries given, e.g:
```
[
"s3://super-awesome-cog-1.tif",
"s3://super-awesome-cog-2.tif",
"s3://super-awesome-cog-3.tif"
]
```
**Re: mercantile**
I believe this PR adds [mercantile](https://github.com/mapbox/mercantile) as a dependency, I am happy to change this if desired! I'm used to mercantile + saw it used in some of the notebooks (so I assumed it might be ok to use). If we'd like to remove mercantile as a …
=> Endpoints to get a list of assets which overlap a point, box, or quadkey

CHANGES.md, docs/advanced/tiler_factories.md, docs/endpoints/mosaic.md, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
ref https://github.com/developmentseed/titiler/discussions/350#discussioncomment-1138576
IMO it's better to use `tile` instead of quadkey, then we could in theory support tile in different TMS (which might not support quadkeys)
cc @mackdelany
=> Assets for tile

CHANGES.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py
ref https://github.com/developmentseed/rio-viz/issues/39
=> remove white space when passing rescale parameters for float32 value

CHANGES.md, src/titiler/core/setup.py, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py
=> Asset expression and fast api

CHANGES.md, src/titiler/application/setup.py, src/titiler/application/tests/routes/test_cog.py, src/titiler/application/titiler/application/main.py
=> use starlette_cramjam compression middleware

CHANGES.md, deployment/k8s/titiler/Chart.yaml, deployment/k8s/titiler/templates/configmap.yaml, deployment/k8s/titiler/templates/deployment.yaml
**Related issue** :
In https://github.com/cogeotiff/rio-tiler/issues/397, I expressed the need to be able to authenticate to the STAC resource if needed.
Implement netrc configuration to allow HTTP basic auth for STAC reader. A configmap is attached to the deployment and mount a netrc config file at `/config/netrc` that is then passed as various env var `NETRC`, `CURLOPT_NETRC`, `CURLOPT_NETRC_FILE` 
=> netrc configmap

docs/examples/notebooks/Working_with_CloudOptimizedGeoTIFF.ipynb, docs/examples/notebooks/Working_with_CloudOptimizedGeoTIFF_simple.ipynb, docs/examples/notebooks/Working_with_MosaicJSON.ipynb, docs/examples/notebooks/Working_with_NumpyTile.ipynb, docs/examples/notebooks/Working_with_STAC.ipynb, docs/examples/notebooks/Working_with_STAC_simple.ipynb, docs/examples/notebooks/Working_with_nonWebMercatorTMS.ipynb
All notebook binder links are broken, missing the word `notebooks` in the file path. This PR fixes the issue.
=> Fixed binder broken links

CHANGES.md, deployment/k8s/titiler/Chart.yaml, deployment/k8s/titiler/templates/ingress.yaml
Update ingress k8s templates to be compatible with latest resource types versions
=> update ingress for latest k8s versions

CHANGES.md, docs/endpoints/cog.md, docs/endpoints/stac.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
we added `tile_buffer` in rio-tiler a while back https://github.com/cogeotiff/rio-tiler/issues/365 but wasn't part of the titiler tile endpoint option 🤷‍♂️
=> add tilebuffer option in tiles endpoint

CHANGES.md, docs/advanced/dependencies.md, docs/endpoints/stac.md, src/titiler/application/setup.py, src/titiler/core/setup.py, src/titiler/core/tests/test_dependencies.py, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/mosaic/setup.py
Update modules version
- `rio-tiler>=3.1`
- `morecantile>=3.1,<4.0` 
- `rio-cogeo>=3.1`
- `cogeo-mosaic>=4.1`
- `fastapi>=0.73`
=> update titiler requirements

src/titiler/core/tests/test_cache_middleware.py, src/titiler/core/titiler/core/middleware.py
While implementing edge caching for a titiler deployment we have a case where underlying source COGs are continually added in real time.  Currently a request that results in `404` `No assets found for tile` has the same `Cache-Control` header as a `200` response and is maintained by the edge cache for the same duration.  In our case we would prefer `404` responses to have a shorter duration in the edge cache so that requests are passed to the origin (where new assets may now be available).  This PR makes the upper range or http codes which include a `Cache-Control` header configurable so that edge caches can exert finer control on error response cache duration.
Extended `core/middleware` to support a configurable upper bound for response codes which include a `Cache-Control` header rather …
=> Make http error cache control behavior configurable.

CHANGES.md, docs/src/advanced/dependencies.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
add `reader_dependency` in BaseTilerFactory to enable passing `Reader`'s option defined by Query/Header/Path parameters.
=> add reader_dependency

src/titiler/core/tests/test_case_middleware.py, src/titiler/core/titiler/core/middleware.py
- Previously if multiple values for a query param were present on a
request (e.g. for a `List[T] = Query(...)` param) only one of the values
would be present after the `LowerCaseQueryStringMiddleware` ran.
- I noticed this issue in our production TiTiler deployment (running version 0.5.1). I copied the `LowerCaseQueryStringMiddleware` and made this change in our app to verify it worked as intended.
- Also added a unit test demonstrating the fix.
- A unit test is included.
=> Include all values for a query param in LowerCaseQueryStringMiddleware

docs/src/dynamic_tiling.md
Fixes a typo that I found while reading the docs
Build and view the docs
n/a
=> Fix typo: Mapgox -> Mapbox

src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
in the `MosaicTilerFactory`.
For https://github.com/developmentseed/titiler/discussions/492
The default `PixelSelectionParams` function doesn't change the existing
behavior (it uses `PixelSelectionMethod.first` if no `pixel_selection`
query param is provided), but a custom function can be used to change
the default behavior.
=> Allow the default pixel_selection method to be overidden 

CHANGES.md, docs/src/advanced/tiler_factories.md, docs/src/endpoints/cog.md, docs/src/endpoints/mosaic.md, docs/src/endpoints/stac.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/index.html, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
This PR adds a simple map viewer 
```
http://127.0.0.1:8081/cog/map?url=https://oin-hotosm.s3.amazonaws.com/5ac626e091b5310010e0d482/0/5ac626e091b5310010e0d483.tif
```
The endpoint takes the same inputs as the Tilejson endpoint (which is used in the viewer)
=> Map viewer

CHANGES.md, docs/src/advanced/customization.md, docs/src/advanced/dependencies.md, src/titiler/core/tests/test_dependencies.py, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/tests/test_factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
This PR refactor the TMS dependency within the TilerFactory to replace it by a simple attribute that gets a `TileMatrixSets` store. The Factory will then create the dependency needed
=> refactor TMS dependency

CHANGES.md, docs/src/endpoints/cog.md, docs/src/endpoints/stac.md, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/index.html, src/titiler/mosaic/titiler/mosaic/factory.py
=> try proj4leaflet to support projection in `/map` viewer

docs/src/examples/code/tiler_with_auth.md, docs/src/examples/code/tiler_with_cache.md
The [auth](https://developmentseed.org/titiler/examples/code/tiler_with_auth/) and [cache](https://developmentseed.org/titiler/examples/code/tiler_with_cache/) examples have an outdated import:
```
from titiler.errors import DEFAULT_STATUS_CODES, add_exception_handlers
```
This minor PR updates the import to:
```
from titiler.core.errors import DEFAULT_STATUS_CODES, add_exception_handlers
```
=> docs: Update titiler.errors to titiler.core.errors in exmaples

docs/src/advanced/performance_tuning.md
Value was equivalent to 20MB instead of desired 200MB
=> docs: Fix recommended CPL_VSIL_CURL_CACHE_SIZE

src/titiler/core/titiler/core/algorithm/dem.py
as per some changes in https://github.com/AndrewAnnex/planetcantile/pull/9, this would expand the default terrainrgb to be more flexible on how the quantizers are defined by accepting floats instead of integers. Shouldn't break or change anything as-is.
=> make terrainrgb interval and baseval floats to support more quantizers

CHANGES.md, src/titiler/core/titiler/core/templates/index.html, src/titiler/extensions/titiler/extensions/templates/cog_index.html, src/titiler/extensions/titiler/extensions/templates/stac_index.html
This PR `fixes` the cog/stac viewer to handle dataset crossing the dateline by using 2 different Layers on each side of the line.
=> add left and right sources to visualize dateline crossing dataset

.github/workflows/check_charts.yaml
The chart install step should not execute if no change has been made in the chart. The condition was not present and the action tried to install the chart in a not initialized cluster. This PR fixes the issue.
=> Conditional Chart install test

docs/src/examples/notebooks/Working_with_CloudOptimizedGeoTIFF_simple.ipynb
in response to this warning..
`%pylab is deprecated, use %matplotlib inline and import the required libraries. Populating the interactive namespace from numpy and matplotlib`
=> %matplotlib inline

CHANGES.md, docs/src/endpoints/cog.md, docs/src/endpoints/stac.md, src/titiler/application/tests/routes/test_cog.py, src/titiler/core/tests/test_dependencies.py, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
closes #631 
This PR adds a `coord-crs=` option to `/point`, `/crop`, `/feature` and `/statistics[POST]` method to allow user to specify the CRS for the input coordinates.
Notes: Sadly it's not as simple for the mosaic endpoint (see https://github.com/developmentseed/cogeo-mosaic/issues/209)
@AndrewAnnex could you double check that's it works for you 🙏
=> add coord-crs options

deployment/k8s/charts/Chart.yaml, deployment/k8s/charts/templates/deployment.yaml, deployment/k8s/charts/values-test.yaml, deployment/k8s/charts/values.yaml
Added additional fields needed for the Helm chart.
=> Added HostPath, ImagePullSecret and TerminationGracePeriodSeconds support

deployment/k8s/charts/Chart.yaml, deployment/k8s/charts/templates/deployment.yaml, deployment/k8s/charts/values.yaml
SecurityContext needed for hardening, which you can define in your values.yaml as follows:
```
securityContext:
capabilities:
drop:
- ALL
readOnlyRootFilesystem: true
allowPrivilegeEscalation: false
runAsNonRoot: true
runAsUser: 1000
podSecurityContext:
readOnlyRootFilesystem: true
runAsNonRoot: true
runAsUser: 1000 
```
=> Added securityContext for k8s

docs/src/advanced/Extensions.md, src/titiler/extensions/README.md
- Fixed a few errors in the thumbnail custom extension example. These corrections have been implemented in both the documentation and the extension readme.
- import rasterio
- use factory for reader
- fixed var names
=> Fix errors in extension example docs

CHANGES.md, src/titiler/core/tests/test_case_middleware.py, src/titiler/core/titiler/core/middleware.py
Small fix where `LowerCaseQueryStringMiddleware` causes query parameter error with pre-signed urls. Co-authoring with @jackharrhy . Closes #678 .
=> fix: `LowerCaseQueryStringMiddleware` should not truncate query parameters

docs/src/intro.md, src/titiler/application/titiler/application/main.py, src/titiler/application/titiler/application/settings.py
As for in discussion #683 
The default settings don't allow to use the `statistics` with geojson `POST` endpoint from a web-app, as only the `GET` method is allowed.
This pull request includes a three-lines change to allow users to allow also the `POST` method by setting `TITILER_API_CORS_ALLOW_METHODS='GET,POST'`.
I know about the ongoing discussion on whether or not to include this middleware in the default application. I am ok with my contribution being rejected if it is not in line with your ideas.
However, I would have saved a day of development if this option were available and documented and it might be help other people not expert in HTTP request to quickly test and deploy their own `titiler` backend.
=> Corse allow methods in env options. #683

CHANGES.md, src/titiler/extensions/titiler/extensions/templates/cog_viewer.html, src/titiler/extensions/titiler/extensions/templates/stac_viewer.html
- Simplify and improve default band selection in RGB viewer for both COG and STAC images
- Removed the special band selection logic that applied to the blue band but not the others.
- Simplified the loading logic so the first three image bands are loaded into the R+G+B channels, respectively, in the viewer.
- Tested by running the app and manually checking things worked as expected
- Run the server, load a COG or STAC item
- #685
=> Simplify band loading

CHANGES.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
instead of needing it to be passed through query params.
- Add a `color_formula_dependency` field to `BaseTilerFactory` & `MosaicTilerFactory` (defaulting to the existing `ColorFormulaParams`) so users can override the logic for supplying a color formula. This lets us define a default color formula from a separate config without needing to include it in the query params for every request.
- Added a dependency to get the `color_formula` value, rather than using a `Query` directly that can't be overridden.
- Via the integration tests, or by using the `color_formula_dependency` in an existing application.
=> Allow a default color_formula to be defined on the factory

CHANGES.md, docs/src/advanced/customization.md, docs/src/examples/code/tiler_with_custom_colormap.md, src/titiler/core/tests/test_CustomCmap.py, src/titiler/core/titiler/core/algorithm/__init__.py, src/titiler/core/titiler/core/dependencies.py
this PR adds an helper function to create ColorMapParams dependency
=> add create_colormap_dependency function

deployment/aws/lambda/handler.py
This PR introduces the ability to host TiTiler on a non-root (non-/) AWS API Gateway route. It's the second attempt after closing developmentseed/titiler#515.
As [suggested by Vincent](https://github.com/developmentseed/titiler/pull/515#issuecomment-1332268220), I passed the `TITILER_API_ROOT_PATH` environment variable to Mangum's `api_gateway_base_path` argument.
Deploy TiTiler as a proxy Lambda to a non-root AWS API Gateway route. Query the various endpoints to confirm they resolve correctly.
FWIW, I tested this change on AWS.
Closes #513
=> Support non-root paths in AWS API Gateway Lambda handler

src/titiler/mosaic/titiler/mosaic/errors.py
Currently, when we mosaic some distant rasters in a large area, leaflet raises a 404 error in the console for every missing tile. Changing from 404 to 204 seems to fix the problem
=> Proposal: Change 404 to 204 NO CONTENT when no asset is found (mosaicjson tiling)

CHANGES.md, docs/mkdocs.yml, docs/src/advanced/dependencies.md, docs/src/advanced/tiler_factories.md, docs/src/endpoints/cog.md, docs/src/endpoints/stac.md, docs/src/external_links.md, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
second take at #714 
This PR adds:
- `retroject` method selection
- `padding` tile option
cc @DanSchoppe
=> add reproject method and padding options

docs/src/examples/code/tiler_with_auth.md, docs/src/intro.md, src/titiler/application/titiler/application/main.py, src/titiler/application/titiler/application/settings.py
This PR is a feature addition, which allows the addition of a global access token to all endpoints.
This feature is important because it allows implementing a basic security, in cases where the endpoint is routed through a machine-to-machine connection. For example, a Ruby API handles all incoming requests and performs the user permissions validation, and then proxies the requests onto a TiTiler server; no requests from outside the Ruby API should be allowed to access the TiTiler endpoints directly.
Please advise if any changed are required for acceptance of this small feature addition!
=> Add global access token setting and validation

CHANGES.md, src/titiler/core/pyproject.toml
=> limit fastapi upper version to avoid starlette breaking change

CHANGES.md, src/titiler/application/titiler/application/main.py, src/titiler/core/pyproject.toml, src/titiler/core/titiler/core/factory.py, src/titiler/extensions/titiler/extensions/viewer.py, src/titiler/extensions/titiler/extensions/wms.py
Fixing #743 - Jinja2 template loading for starlette >=0.28 
using the env parameter rather than passing in the params to environment
Try startup titiler with starlette >=0.28 
closes #743
=> fix template loading for starlette >= 0.28

docs/src/examples/code/tiler_with_custom_tms.md
Hiya, 
Just playing around with custom tile matrix sets, and had to change the example from the docs to get it working. 
This is what I did, but still have quite a shallow understanding, so might not be the best way. Happy to alter if needed.
=> Update custom tms code example

src/titiler/application/tests/routes/test_cog.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/wmts.xml
Adds a `use_epsg` parameter to the WMTS endpoint, which changes the format of the CRS for the tile matrix set. This is needed to support ArcMap, which doesn't like the opengis.net-style CRS in the `SupportedCRS`.
Also adds an `escape` to the URLs in the WMTS template, as multiple query parameters were breaking XML parsing b/c of the `&`.
I've added unit tests. To manually test, you can hit a **titiler** WMTS endpoint with the parameter, e.g. `http://localhost:8000/cog/WMTSCapabilities.xml?url=your-url-here&use_epsg=true` and check out the `SupportedCRS` field.
- Should resolve https://github.com/developmentseed/titiler/discussions/732
This is an ArcMap WMTS configuration against **titiler** endpoint without any modifications:
The layer doesn't load:
Adding the `use_epsg` parameter:
It …
=> Add `use_epsg` parameter to WMTS endpoint

deployment/azure/README.md, deployment/azure/app/__init__.py, deployment/azure/host.json
I've updated the Azure deployment documentation and sample to reflect changes to the titiler codebase (https://github.com/developmentseed/titiler/pull/537), fixes to upstream dependencies ([starlette](https://github.com/encode/starlette/issues/1320)), and updates to the Azure Python function wrapper package.
The updates to the Azure sample match the main sample application. The others were made through trial and error.
No tests for these examples, run as-is.
* changes to the sample required by changes made here: https://github.com/developmentseed/titiler/pull/537
* re-enabling of middleware based on this issue being resolved: https://github.com/encode/starlette/issues/1320
=> Update Azure deployment example

CHANGES.md, src/titiler/core/titiler/core/algorithm/base.py, src/titiler/core/titiler/core/algorithm/dem.py, src/titiler/core/titiler/core/algorithm/index.py, src/titiler/core/titiler/core/factory.py
@vincentsarago 
Based on the discussion here (https://github.com/developmentseed/titiler/discussions/760), I added min/max settings for algorithms parameters. I think these min/max values can be useful to create UI parts dynamically from titiler endpoint.
some parameters are straightforward to set min/max values, but some are not easy to set. Could you also check these min/max values are appropriate?
settings are shown as follow.
- Hillshade
```python
azimuth: int = Field(90, ge=0, lt=360)
angle_altitude: float = Field(90.0, ge=-90.0, lt=90.0)
buffer: int = Field(3, ge=0, lt=99)
```
- Contours
```python
increment: int = Field(35, ge=0, lt=999)
thickness: int = Field(1, ge=0, lt=10)
minz: int = Field(-12000, ge=-99999, lt=99999)
maxz: int = Field(8000, ge=-99999, lt=99999)
```
- TerrainRGB …
=> feat: added min and max value to algorithms

src/titiler/core/titiler/core/algorithm/dem.py
@vincentsarago I am sorry, I did a mistake for maximum value setting for DEM algorithms. It should be `le (maximum)` instead of `lt (exclusiveMaximum)`.
I fixed them, and the new response of `/algorithms` endpoint is shown below
<details>
<summary>/algorithms endpoint response</summary>
```json
{
"hillshade":{
"title":"Hillshade",
"description":"Create hillshade from DEM dataset.",
"inputs":{
"nbands":1
},
"outputs":{
"nbands":1,
"dtype":"uint8",
"min":null,
"max":null
},
"parameters":{
"azimuth":{
"default":90,
"maximum":360,
"minimum":0,
"title":"Azimuth",
"type":"integer"
},
"angle_altitude":{
"default":90,
"maximum":90,
"minimum":-90,
"title":"Angle Altitude",
"type":"number"
},
"buffer":{
"default":3,
"maximum":99,
"minimum":0,
"title":"Buffer",
"type":"integer"
}
}
},
"contours":{ …
```
=> fix: changed lt(exclusiveMaximum) to le(maximum) for DEM algorithms

CHANGES.md, src/titiler/application/titiler/application/settings.py
Closes https://github.com/developmentseed/titiler/issues/799
Context:
`pydantic-settings` Released a new update (`2.2.0`) that breaks TiTiler API when using a `.env` file that contains variables inside.
This PR will solve the issue by adding `extra="ignore"` to the `pydantic_settings.SettingsConfigDict` object.
=> Adding extra="ignore" option to fix pydantic_settings.SettingsConfigDict issue with environement variables

docs/mkdocs.yml, docs/src/overrides/partials/integrations/analytics/plausible.html
Relevant lonboard prs:
- https://github.com/developmentseed/lonboard/pull/467 
- https://github.com/developmentseed/lonboard/pull/468
I set up the initial page tracking, but we have to wait for this to be deployed and for the first page load to register the search and up/down vote events
=> Add plausible analytics

src/titiler/core/pyproject.toml
Replace the `fastapi` dependency with `fastapi-slim`. 
See https://github.com/tiangolo/fastapi/pull/11522 for details. My brief summary of what happened in the FastAPI project: Installing `fastapi` now comes along with dependencies that are helpful for development and deployment, at the expense of installing more dependencies. Since tiler applications are opinionated in their dependencies additional dependencies raise the risk of conflicts, albeit slightly. This change keeps the same dependencies that FastAPI pulls in transitively.
Swap the dependency specification, meaning nothing would change :smile:.
Unit tests, standard CI should be more than enough because this result in nothing changing.
N/A.
=> fastapi-slim replaces fastapi

docs/src/examples/notebooks/Working_with_STAC_simple.ipynb
- Make a tutorial easier to understand.
- Moved some code comments into markdown cells and expanded them.
- Verify that the notebook cells render correctly.
=> Add band index description to markdown cells

CHANGES.md, src/titiler/core/tests/test_factories.py, src/titiler/core/titiler/core/templates/wmts.xml
=> fix Tiles URL encoding in WMTS XML doc

CHANGES.md, src/titiler/extensions/titiler/extensions/templates/cog_viewer.html, src/titiler/extensions/titiler/extensions/templates/stac_viewer.html
- I am testing my own TiTiler instance reading some COGs stored at my own S3 storage. I realized that when passing the signed URL for the resource to the `/viewer` endpoint, it won't work as the first query to `/info` doesn't go through. I tried encoding my urls with an online tool (https://www.urlencoder.org/) and it works perfectly fine. Calling the `/info` endpoint from the docs works as expected with the URL as-is, so I took a look at the Viewer template.
- When testing these urls using the docs, the curl command I get as result looks to have the URL properly encoded.
- In the Viewer template, I added the [`encodeURIComponent`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) function to the introduced URL that does the same thing as …
=> fix: Encode URL for cog_viewer and stac_viewer

CHANGES.md, docs/src/benchmark.html, src/titiler/application/titiler/application/templates/index.html, src/titiler/core/titiler/core/templates/map.html, src/titiler/extensions/titiler/extensions/templates/cog_viewer.html, src/titiler/extensions/titiler/extensions/templates/stac_viewer.html
- Removing Bootstrap script loaded from Minnesota DNR site, switched to a well-known CDN.
- Adding [subresource integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity) attributes for all script tags / css links to improve cross-site scripting on domains which deploy titiler html pages.
Should only need to verify the generated API pages all still look / function as expected.
=> Improve XSS security

src/titiler/extensions/titiler/extensions/templates/cog_viewer.html, src/titiler/extensions/titiler/extensions/viewer.py
If someone is using the `/cog/viewer` endpoint to figure out which render parameters make sense for their dataset it would be nice to add a `Show Render Parameters` button. It would also be nice to be able to share a link to a map with those parameters applied so the user could send someone a link to the exact image that they decided on. It might be better to link to `/cog/viewer` since `/cog/map` is deprecated, but right now you can't set render parameters in that endpoint (just `url`).
This idea came from Team 4 in the IMPACT X-athon with @anayeaye    @smk0033 @unhipcat
=> feature: add links for render parameters and /cog/map link to /cog/viewer dashboard

src/titiler/application/pyproject.toml, src/titiler/application/titiler/application/main.py
Also set default compression level to 6 so we don't default to 11 for Brotli 
ref: https://github.com/milesgranger/cramjam/issues/187
=> update starlette-cramjam dependency

src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/wmts.xml, src/titiler/mosaic/titiler/mosaic/factory.py
second take at #995 
cc @AndrewAnnex
=> use BoundingBox instead of WGS84BoundingBox in wmts when tms is not based on WGS84

.github/data/urls.txt
The [benchmarks for the past few commits](https://developmentseed.org/titiler/benchmark.html) haven't been working for Web Mercator Quad tiles because the deprecated `/tiles/{z}/{x}/{y}.{format}` endpoint was removed in https://github.com/developmentseed/titiler/pull/943. This updates the path used for those benchmarks.
=> Update from deprecated path in benchmarks

CHANGES.md, src/titiler/application/tests/routes/test_cog.py, src/titiler/core/titiler/core/dependencies.py, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/map.html, src/titiler/core/titiler/core/templates/wmts.xml, src/titiler/extensions/titiler/extensions/wms.py, src/titiler/mosaic/titiler/mosaic/factory.py
This PR takes some modification from #1007 
- update WMTS template to add `layers` (would be used by STAC+render) 
- reorder dependencies (for OpenAPI docs)
- fix bounds overflow on `map` viewer
=> add `Layers` to wmts and reorder dependencies

CHANGES.md, src/titiler/core/titiler/core/templates/map.html
The `minZoom` and `maxZoom` parameters in the `tileLayer` class just control which zoom levels on which tiles from the layer will be displayed. Setting `minNativeZoom` and `maxNativeZoom` to the `tilejson` `minzoom` and `maxzoom` makes more sense and allows us to show tiles from layers where the default `maxzoom` is very low (e.g. 0) which can happen for very low-resolution datasets.
> `maxNativeZoom`: Maximum zoom number the tile source has available. If it is specified, the tiles on all zoom levels higher than maxNativeZoom will be loaded from maxNativeZoom level and auto-scaled.
[leaflet API docs](https://leafletjs.com/reference.html#tilelayer-maxnativezoom)
=> set min/maxNativeZoom in tileLayer instead of min/maxZoom

deployment/azure/README.md
Changed:
- Python runtime version from 3.8 to 3.9 (azure function no longer supports 3.8)
- Functions version was updated from 3 to 4 (you wont be able to create a new app function on version 3). 
- Added the --python flag at the end of the publishing command, infering the FUNCTIONS_WORKER_RUNTIME.
Here's some testing I made that backs the points above:
Alternatively, I have added variables instead of fixed values for container name and app name, given that it must be a unique name for each new instance and that can confuse people not familiar with how blob storage works.
=> Updating Azure Functions Commands

README.md
Just updates the README to mention support for multidimensional datasets
=> docs: add multidimensional data via xarray as supported on readme

docs/src/external_links.md
- Fix typo in documentation URL to ensure correct linking
- Corrected URL from https://github.com/developmentseed/titiler-images to https://github.com/developmentseed/titiler-image
- Improve documentation accuracy for better user experience
- Identified incorrect URL in the documentation
- Updated the URL to the correct destination
- Verified the new URL works as expected
- Clone the repository
- Navigate to the updated documentation
- Click on the corrected URL to verify it leads to the intended destination
- Alternatively, you can check the rendered documentation on the PR preview
No related issues. This is a straightforward documentation fix.
=> Fix typo in documentation(docs/src/external_links.md) URL

CHANGES.md, src/titiler/application/LICENSE, src/titiler/application/pyproject.toml, src/titiler/core/LICENSE, src/titiler/core/pyproject.toml, src/titiler/extensions/LICENSE, src/titiler/extensions/pyproject.toml, src/titiler/mosaic/LICENSE, src/titiler/mosaic/pyproject.toml, src/titiler/xarray/LICENSE, src/titiler/xarray/pyproject.toml
closes #1041 
This pr does:
- adds proper licenses files into each packages 
- migrate from `pdm-pep517` to `pdm-backend` 
- update package name to `-` separation (e.g `titiler.core -> titler-core`) 
I've confirmed locally the structure of the package should not change neither how the name resolves
=> update build backend and others

CHANGES.md, src/titiler/application/tests/test_main.py, src/titiler/application/titiler/application/main.py
This is a hasty attempt to add `rasterio.show_versions()` to the `healthz` endpoint as discussed in https://github.com/developmentseed/titiler/discussions/731 . It "works" but formatting could be improved...
```bash
curl -X 'GET' \
'http://127.0.0.1:8000/healthz' \
-H 'accept: application/json' | jq
```
```
{
"Hello from titiler!": [
"rasterio info:",
"  rasterio: 1.4.3",
"      GDAL: 3.9.3",
"      PROJ: 9.4.1",
"      GEOS: 0.0.0",
" PROJ DATA: /Users/scotthenderson/miniforge3/envs/titiler/lib/python3.11/site-packages/rasterio/proj_data",
" GDAL DATA: /Users/scotthenderson/miniforge3/envs/titiler/lib/python3.11/site-packages/rasterio/gdal_data",
"",
"System:",
"    python: 3.11.11 | packaged by conda-forge | (main, Dec  5 2024, 14:21:42) [Clang 18.1.8 ]",
"executable: …
```
=> Include rasterio.show_versions() output in healthz endpoint

CHANGES.md, src/titiler/core/titiler/core/middleware.py
Earlier code manually built the query string by concatenating strings and handling URL encoding one parameter at a time. New code uses list comprehension and built-in urlencode. cc @vincentsarago
=> improve query string handling in LowerCaseQueryStringMiddleware using urlencode

src/titiler/core/titiler/core/middleware.py
Since any() doesn't require a materialized list, simplify the code to use generator expression instead of a list comprehension. Makes it ~tiny bit performant and readable. cc @vincentsarago
=> style: use generator expression in CacheControlMiddleware.any()

src/titiler/xarray/README.md
There appears to be typo at two places in the titiler-xarray's readme @vincentsarago
=> doc: fix xarray readme typo

src/titiler/xarray/tests/test_io_tools.py
Keys for Zarr stores should be ASCII strings in both the v2 and v3 specifications, but Zarr-Python 3.0 is less lenient than Zarr-Python 2.0 and does not cast types. This PR updates the tests to use a valid group key (str rather than int).
Progress towards https://github.com/developmentseed/titiler/issues/1068
=> Fix type used for group argument in xarray tests

CHANGES.md, src/titiler/xarray/pyproject.toml, src/titiler/xarray/titiler/xarray/io.py
Adds support for both opening Zarr stores using either Zarr-Python 2 or Zarr-Python 3.
Fixed #1068
=> Support Zarr-Python 3

src/titiler/core/tests/test_algorithms.py, src/titiler/core/titiler/core/algorithm/__init__.py, src/titiler/core/titiler/core/algorithm/dem.py
Adds a slope algorithm that computes the slope of a raster in degrees from the horizontal. The intended range of output values is from 0 (horizontal) to 90 (vertical). 
Since it's possible to convert to percentage slope using raster band math (`b1/90`), I didn't bother to include any parameters for controlling wether or not the algorithm outputs degrees or percent slope.
The only parameter for the algorithm is `buffer`, which follows the hillshade defaults. This can be used to reduce edge artifacts in the computed slope. Users should specify the same buffer for the tile request as they do for the algorithm parameter (which defaults to 3).
=> Add slope algorithm

CHANGES.md, src/titiler/core/titiler/core/algorithm/dem.py
This is just a small tweak to add more output metadata to the slope algorithm.
=> Add output min and max metadata to slope algorithm

CHANGES.md, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/map.html
With this change if a user right clicks on a point in the map viewer it will send a query to `/point` for the layer and display the values in a popup. If the layer has multiple bands it will show all of the bands in a table.
single-band `cog`:
multi-band `cog`:
multi-band `stac`:
=> add point query on right-click to map viewer

docs/src/advanced/Algorithms.md, src/titiler/core/tests/test_algorithms.py, src/titiler/core/titiler/core/algorithm/dem.py, src/titiler/extensions/titiler/extensions/templates/cog_viewer.html
Can be tested via 
> 'tiles': ['http://localhost:8000/cog/tiles/WebMercatorQuad/{z}/{x}/{y}@1x.png?algorithm=terrainrgb&algorithm_params={"use_nodata_height":true,"nodata_height":0.0}&nodata=-9999&url=https://3d.iconem.com/greece/amphipolis/Amphipolis_general_dsm_10cm_cog_cropped_alpha.tif'] 
**TODO**: Also should take a moment to add suggested updates from discussion https://github.com/developmentseed/titiler/discussions/1110
=> Fix TerrainRGB algorithm and param user-controlled nodata-height

CHANGES.md, docs/src/advanced/endpoints_factories.md, docs/src/endpoints/cog.md, docs/src/endpoints/mosaic.md, docs/src/endpoints/stac.md, src/titiler/core/titiler/core/factory.py, src/titiler/mosaic/titiler/mosaic/factory.py
ref https://github.com/developmentseed/titiler/issues/753 https://github.com/developmentseed/titiler/issues/1126#issuecomment-2789156024
=> rename /map to /map.html

CHANGES.md, src/titiler/core/titiler/core/templates/map.html
By setting `minNativeZoom` we were constructing low zoom tiles from many higher-zoom tile requests! This is not the intended effect of the minzoom setting. We can still overzoom by using maxNativeZoom.
=> fix: use minZoom instead of minNativeZoom

CHANGES.md, docs/src/advanced/endpoints_factories.md, src/titiler/xarray/tests/test_factory.py, src/titiler/xarray/titiler/xarray/dependencies.py, src/titiler/xarray/titiler/xarray/factory.py
add `/preview` endpoint to Xarray TilerFactory.
Those endpoint are disabled by default because Xarray dataset might not be suitable for `previews`
=> [xarray] add preview endpoints

CHANGES.md, src/titiler/core/titiler/core/factory.py, src/titiler/core/titiler/core/templates/map.html, src/titiler/core/titiler/core/templates/wmts.xml, src/titiler/mosaic/titiler/mosaic/factory.py
This PR adds `attribution` field in /tilejson.json, /tiles and /tiles/{tileMatrixSetId} responses. The attribution is defined using `TITILER_DEFAULT_ATTRIBUTION` environment variable.
ref https://github.com/developmentseed/titiler/discussions/1214
cc @mradamcox
=> add attribution
